//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SuperProgress.rc
//
#define IDD_SUPERPROGRESS_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDB_PROGRESS                    129
#define IDC_GO                          1001
#define IDC_STEPIT                      1002
#define IDC_MIN                         1003
#define IDC_MAX                         1004
#define IDC_STEP                        1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
