//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ClrWellDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLRWELLDEMO_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDC_COLORBTN                    1000
#define IDC_BLACK                       1002
#define IDC_BLUE                        1003
#define IDC_GREEN                       1004
#define IDC_AQUA                        1005
#define IDC_RED                         1006
#define IDC_PURPLE                      1007
#define IDC_SILVER                      1008
#define IDC_WHITE                       1009
#define IDC_GRAY                        1010
#define IDC_MAROON                      1011
#define IDC_FUSCHIA                     1012
#define IDC_TEAL                        1013
#define IDC_OLIVE                       1014
#define IDC_NAVY                        1015
#define IDC_YELLOW                      1016
#define IDC_LIME                        1017
#define IDC_NUMCOLS_SPIN                1019
#define IDC_NUMCOLS_EDIT                1020
#define IDC_OUTERBORDER_EDIT            1021
#define IDC_OUTERBORDER_SPIN            1022
#define IDC_INNERBORDER_EDIT            1023
#define IDC_INNERBORDER_SPIN            1024
#define IDC_WELLHEIGHT_EDIT             1025
#define IDC_WELLHEIGHT_SPIN             1026
#define IDC_ISOTROPICWELLS              1027
#define IDC_SHAPE                       1028
#define IDC_SHAPE2                      1029
#define IDC_WIDTHSLIDER                 1030
#define IDC_UPDATE                      1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
