//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tetris.rc
//
#define IDD_TETRIS_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_OptionsDlg                  129
#define IDR_SndLevelWarp                130
#define IDR_SndPlace                    131
#define IDR_SndKey                      132
#define IDB_Splash                      133
#define IDD_About                       135
#define IDB_Digit0                      136
#define IDB_Digit1                      138
#define IDB_Digit2                      139
#define IDB_Digit3                      140
#define IDB_Digit4                      141
#define IDB_Digit5                      142
#define IDB_Digit6                      143
#define IDB_Digit7                      144
#define IDB_Digit8                      145
#define IDB_Digit9                      146
#define IDB_DigitBlank                  147
#define IDR_SndGameOver                 148
#define IDR_MidiRussians                151
#define IDM_Fairy                       152
#define IDM_Wind                        153
#define IDR_SndKalinka                  155
#define IDI_MoveLeft                    156
#define IDI_MoveRight                   157
#define IDD_ScoreDlg                    157
#define IDI_Place                       158
#define IDM_Kalinka                     158
#define IDI_Rotate                      159
#define IDM_WindOfChange                161
#define IDD_GameOverDlg                 162
#define IDB_RedPlace                    163
#define IDB_Background                  164
#define IDI_Boom_1                      165
#define IDI_Boom_2                      166
#define IDR_SndLineComplete             166
#define IDI_Boom_3                      167
#define IDD_VolumeCtrl                  167
#define IDI_Boom_4                      168
#define IDD_Help                        168
#define IDI_Boom_5                      169
#define IDI_Boom_6                      170
#define IDI_Boom_7                      171
#define IDI_Boom_8                      172
#define IDI_Boom_9                      173
#define IDI_Boom_10                     174
#define IDC_EditWidth                   1002
#define IDC_EditHeight                  1003
#define IDC_SpinWidth                   1004
#define IDC_SpinHeight                  1005
#define IDC_CheckGrid                   1006
#define IDC_BtnStart                    1007
#define IDC_GameBoard                   1008
#define IDC_ChkSound                    1010
#define IDC_Score                       1011
#define IDC_Lines                       1012
#define IDC_Level                       1013
#define IDC_PiecePreview                1015
#define IDC_MailTo                      1016
#define IDC_NoWarranty                  1017
#define IDC_Concept                     1018
#define IDC_Title                       1019
#define IDC_CodeGuru                    1020
#define IDC_WebCodeGuru                 1021
#define IDC_MoreCodeGuru                1022
#define IDC_Resource_1                  1023
#define IDC_Propeller                   1024
#define IDC_Credits                     1026
#define IDC_Pause                       1027
#define IDC_ChkMusic                    1028
#define IDC_ComboMusic                  1029
#define IDC_MoveLeft                    1030
#define IDC_MoveRight                   1031
#define IDC_Place                       1032
#define IDC_Rotate                      1033
#define IDC_ListScore                   1035
#define IDC_Splash                      1036
#define IDC_MusicBox                    1037
#define IDC_GameOver                    1038
#define IDC_ExtendedFigureSet           1039
#define IDC_TxtScore                    1040
#define IDC_TxtLines                    1041
#define IDC_TxtLevel                    1042
#define IDC_TxtSquareWidth              1043
#define IDC_TxtSquareHeight             1044
#define IDC_GroupBoard                  1045
#define IDC_GroupSound                  1046
#define IDC_TxtSoundCard                1047
#define IDC_Volume                      1048
#define IDC_Help                        1049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
