//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MixerControls.rc
//
#define IDD_SPEAKER_DIALOG              103
#define IDD_WAVEIN_DIALOG               104
#define IDR_MAINFRAME                   128
#define IDD_MAIN_DIALOG                 129
#define IDR_MAIN_MENU                   130
#define IDD_ABOUT_DIALOG                132
#define IDD_INFO_DIALOG                 133
#define IDB_TREE_BITMAP                 134
#define IDD_VOICE_DIALOG                134
#define IDC_MAIN_VOLUME                 1003
#define IDC_MAIN_LEFT                   1004
#define IDC_CD_VOLUME                   1005
#define IDC_CD_MUTE                     1006
#define IDC_CD_BALANCE                  1007
#define IDC_MAIN_MUTE                   1008
#define IDC_MAIN_BALANCE                1009
#define IDC_WAVE_VOLUME                 1010
#define IDC_MIKE_GAIN                   1011
#define IDC_MAIN_RIGHT                  1011
#define IDC_WAVE_MUTE                   1012
#define IDC_WAVE_BALANCE                1013
#define IDC_SYNTH_VOLUME                1014
#define IDC_SYNTH_MUTE                  1015
#define IDC_SYNTH_BALANCE               1016
#define IDC_AUX_VOLUME                  1017
#define IDC_AUX_MUTE                    1018
#define IDC_AUX_BALANCE                 1019
#define IDC_MIKE_VOLUME                 1020
#define IDC_MIKE_MUTE                   1021
#define IDC_MIKE_BALANCE                1022
#define IDC_MAIN_BASS                   1023
#define IDC_MAIN_TREBLE                 1024
#define IDC_CD_SELECT                   1025
#define IDC_PC_VOLUME                   1025
#define IDC_MIKE_SELECT                 1026
#define IDC_PC_BALANCE                  1026
#define IDC_LINEIN_SELECT               1027
#define IDC_PC_MUTE                     1027
#define IDC_SYNTH_SELECT                1030
#define IDC_PEAK_STATIC                 1032
#define IDC_MAIN_STATIC                 1057
#define IDC_GAIN_STATIC                 1058
#define IDC_LINEIN_STATIC               1059
#define IDC_SYNTH_STATIC                1060
#define IDC_MIKE_STATIC                 1061
#define IDC_CD_STATIC                   1062
#define IDC_WAVE_STATIC                 1063
#define IDC_BASS_STATIC                 1064
#define IDC_TREBLE_STATIC               1065
#define IDC_INPUT_STATIC                1066
#define IDC_PC_STATIC                   1066
#define IDC_NAME_STATIC                 1067
#define IDC_INFO_TREE                   1068
#define IDC_INFO_LIST                   1070
#define IDC_ENHANCE_CHECK               1072
#define IDC_GAIN_SPIN                   1073
#define ID_SPEAKERS                     32771
#define ID_WAVEIN                       32772
#define ID_VOICEIN                      32773
#define ID_INFO_DLG                     32774
#define ID_INFO                         32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
