//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CButtonX.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CBUTTONX_DIALOG             102
#define IDD_HOTBUTTON_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDB_XMED                        130
#define IDB_HOT_INTERNAL                130
#define IDB_CHKMED                      131
#define IDB_HOT_CONTACT                 136
#define IDC_CONTACTS                    1000
#define IDC_HOT                         1001
#define IDC_USE_BITMAP                  1002
#define IDC_X_BMP                       1003
#define IDC_CHECK_BMP                   1004
#define IDC_FOLDER_BMP                  1005
#define IDC_PAPER_BMP                   1006
#define IDC_PRINTER_BMP                 1007
#define IDC_RARROW                      1008
#define IDC_LARROW                      1009
#define IDC_LED                         1010
#define IDC_ELLIPSE                     1011
#define IDC_BINOC                       1012
#define IDC_CLOCK_BMP                   1013
#define IDC_REDFLAG_BMP                 1014
#define IDC_BANNED_BMP                  1015
#define IDC_APP_DEFINED                 1016
#define IDC_MAILTO                      1018
#define IDC_ABOUT                       1019
#define IDC_WEBSITE                     1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
