//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OutBarDemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_OUTBARTYPE                  129
#define IDB_IMAGELIST                   132
#define IDB_SMALL_IMAGELIST             133
#define IDC_NODRAGGING                  268
#define IDC_DRAGGING                    1320
#define IDC_HANDCUR                     3010
#define ID_SMALL                        32771
#define ID_GFX_SMALLICON                50000
#define ID_GFX_LARGEICON                50001
#define ID_GFX_RENAMEITEM               50002
#define ID_GFX_REMOVEITEM               50003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
