//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TLView.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TLVIEWTYPE                  129
#define IDD_TREE_LIST_VIEW              131
#define IDB_DOCS_IMAGES                 133
#define IDB_HEADER                      343
#define IDC_TREELIST                    346

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
