//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Sample.rc
//
#define IDC_SCAN                        3
#define IDD_SAMPLE_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_PAGE1                       129
#define IDD_PAGE2                       130
#define IDD_PAGE3                       131
#define IDC_LIST                        1000
#define IDC_PAGE1                       1001
#define IDC_PAGE2                       1002
#define IDC_PAGE3                       1003
#define IDC_COMBO                       1004
#define IDC_PLACEHOLDER                 1005
#define IDC_MONTHCALENDAR1              1006
#define IDC_TREE                        1008
#define IDC_CUSTOM1                     1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
