//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Demo.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DEMOTYPE                    129
#define IDB_RADIOOFF                    130
#define IDB_CHECKOFF                    131
#define IDB_RADIOON                     132
#define IDB_CHECKON                     133
#define IDB_ITEMS                       134
#define IDD_OPTIONS                     135
#define IDC_OPTIONS                     1000
#define IDM_SETTINGS                    32771
#define IDM_SELECT                      32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
