//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DemoTBarE.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DEMOTBTYPE                  129
#define IDB_TOOLBAR_COLD                135
#define IDB_TOOLBAR_HOT                 136
#define IDR_HOTBAR                      137
#define ID_BACK                         32774
#define ID_FORWARD                      32775
#define ID_STOP                         32776
#define ID_REFRESH                      32777
#define ID_HOME                         32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
