//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ReStart.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_RESTART_FORM                101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_OUTPUT_WAVE       128
#define IDR_RESTARTYPE                  129
#define IDR_MAINFRAME_INPUT_WAVE        130
#define IDR_MAINFRAME_WAVE              131
#define IDB_MENUCHK                     132
#define IDB_PLAYU                       134
#define IDB_PLAYD                       135
#define IDB_PAUSEU                      136
#define IDB_PAUSED                      137
#define IDB_REWINDU                     138
#define IDB_REWINDD                     139
#define IDB_FORWINDU                    140
#define IDB_FORWINDD                    141
#define IDB_STOPU                       142
#define IDB_STOPD                       143
#define IDB_RECORDU                     144
#define IDB_RECORDD                     145
#define IDC_SELECT                      146
#define IDD_INFO_BAR                    150
#define IDC_PLAY                        1002
#define IDC_PAUSE                       1003
#define IDC_REWIND                      1004
#define IDC_FORWIND                     1005
#define IDC_STOP                        1006
#define IDC_RECORD                      1007
#define IDC_COMBO_MONO                  1009
#define IDC_COMBO_KHZ                   1010
#define IDC_COMBO_BITS                  1011
#define IDC_COMBO_RECORDING_TIME        1012
#define IDC_LIST1                       1013
#define IDC_STATIC_SOURCE               1014
#define IDC_STATIC_FILENAME             1015
#define IDC_STATIC_FORMAT               1016
#define IDC_STATIC_SIZE                 1017
#define IDC_STATIC_TIME                 1018
#define ID_VIEW_INFO_BAR                32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
