//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Real.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REAL_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDB_MAIN                        130
#define IDB_LOGO                        130
#define IDC_LOGO                        132
#define IDB_SYSTEM                      133
#define IDR_SYSTEM                      135
#define IDM_IMAGE                       32771
#define IDM_EXIT                        32772
#define IDM_IMAGE2                      32773
#define IDM_IMAGE3                      32774
#define IDM_IMAGE4                      32775
#define IDM_IMAGE5                      32776
#define IDM_ABOUT                       32777
#define IDM_CLOSE                       32778
#define IDM_MOVE                        32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
