//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WFDemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_WFDEMO_FORM                 101
#define IDC_CHART2D                     101
#define IDC_CHART3D                     102
#define IDR_MAINFRAME                   128
#define IDR_WFDEMOTYPE                  129
#define IDC_START                       1000
#define IDC_VIEW                        1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
