//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GfxList.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_GFXLIST_FORM                101
#define IDD_GFX_CUSTOMIZECOL            102
#define IDD_GFX_FORMATCOL               103
#define IDC_IPEDIT                      104
#define IDR_MAINFRAME                   128
#define IDR_GFXLISTYPE                  129
#define IDR_LISTMENUBMP                 129
#define IDD_TEST_DIALOG                 130
#define IDD_GFX_FORMATCOL_ITA           131
#define IDD_GFX_CUSTOMIZECOL_ITA        132
#define IDB_ARANLIST                    134
#define IDB_ARANCOL                     135
#define IDB_BITMAP1                     138
#define IDB_BITMAP2                     143
#define IDC_LIST1                       1008
#define IDC_ACTCOL                      1009
#define IDC_ADD                         1010
#define IDC_REMOVE                      1011
#define IDC_MOVEUP                      1012
#define IDC_MOVEDOWN                    1013
#define IDC_FREECOL                     1014
#define IDC_CB_FORMAT                   1015
#define IDC_CD_LABEL                    1016
#define IDC_LABEL_DT                    1017
#define IDC_WIDTH                       1018
#define IDC_RD_RIGHT                    1019
#define IDC_RD_CENTER                   1020
#define IDC_RD_LEFT                     1021
#define IDC_FMT                         1022
#define ID_CUSTOMHEADER                 32771
#define ID_TRY1                         32772
#define ID_TESTCAT                      32774
#define ID_ADDANITEM                    32775
#define ID_TRYBITMAP1                   32776
#define ID_TRYBITMAP2                   32777
#define ID_BLENDBMP                     32778
#define ID_DRAGGABLECOL                 32780
#define ID_GRIDH                        32781
#define ID_GRIDV                        32782
#define ID_TESTDAO                      32783
#define ID_FORMATHEADER                 32800
#define ID_GFX_FORMATHEADER             32801
#define ID_GFX_CUSTOMIZEHEAD            32802
#define ID_GFX_SORTASC                  32803
#define ID_GFX_SORTDESC                 32804
#define ID_AUTOPREVIEW                  33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
