//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DualListDemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DUALLISTDEMO_FORM           101
#define IDD_FORM_DUAL_LIST_DEMO         101
#define IDR_MAINFRAME                   128
#define IDR_DUALLITYPE                  129
#define IDD_DIALOG_DUAL_LIST_DEMO       130
#define IDD_PROP_PAGE_DUAL_LIST_DEMO    131
#define IDC_FV_LIST_AVAILABLE           1000
#define IDC_FV_ADD                      1001
#define IDC_FV_ADD_ALL                  1002
#define IDC_FV_REMOVE                   1003
#define IDC_FV_REMOVE_ALL               1004
#define IDC_FV_MOVE_UP                  1005
#define IDC_FV_MOVE_DOWN                1006
#define IDC_FV_LIST_CHOOSEN             1007
#define IDC_DLG_LIST_AVAILABLE          1008
#define IDC_DLG_ADD                     1009
#define IDC_DLG_ADD_ALL                 1010
#define IDC_DLG_REMOVE                  1011
#define IDC_DLG_REMOVE_ALL              1012
#define IDC_DLG_LIST_CHOOSEN            1013
#define IDC_DLG_MOVE_UP                 1014
#define IDC_DLG_MOVE_DOWN               1015
#define IDC_PP_LIST_AVAILABLE           1016
#define IDC_PP_ADD                      1017
#define IDC_PP_ADD_ALL                  1018
#define IDC_PP_REMOVE                   1019
#define IDC_PP_REMOVE_ALL               1020
#define IDC_PP_MOVE_UP                  1021
#define IDC_PP_MOVE_DOWN                1022
#define IDC_PP_LIST_CHOOSEN             1023
#define ID_DUALLISTTESTS_DUALLISTDIALOG 32771
#define ID_DUALLISTTESTS_DUALLISTPROPERTYPAGE 32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
