//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dlg_ttbar.rc
//
#define ID_TOP                          3
#define ID_BOTTOM                       4
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_NEW                         102
#define IDS_LIST                        103
#define IDS_CUT                         104
#define IDS_PRINT                       105
#define IDS_EXIT                        106
#define IDR_MAINFRAME                   128
#define IDD_DLG_TTBAR_DIALOG            129

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
