//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WizDlg.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_WIZARDBASE                  102
#define IDR_MAINFRAME                   128
#define IDR_WIZDLGTYPE                  129
#define IDD_TESTPAGE1                   130
#define IDD_TESTPAGE2                   131
#define IDB_WIZARD_BACK                 131
#define IDD_TESTPAGE3                   132
#define IDC_EDIT1                       1000
#define IDC_STATIC1                     1009
#define IDC_BT_TITLE                    1010
#define IDC_BACK                        1011
#define IDC_PAGEFRAME                   1012
#define IDC_PICTURE                     1013
#define ID_TEST_WIZARD                  32771
#define ID_CUSTOM_WIZARD                32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
