//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CustomMoreWindows.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CUSTOMTYPE                  129
#define IDC_ACTIVATE                    30002
#define IDC_CLOSE                       30003
#define IDD_WINDOWLIST                  30021
#define IDC_WINDOWLIST                  30038
#define IDC_SAVE                        30134

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
