//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MidiPlayer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MIDIPLAYER_DIALOG           102
#define IDS_MAINFRAME                   102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDC_PROGRESS                    1000
#define IDC_PLAY                        1002
#define IDC_MAILTO                      1003
#define IDC_STOP                        1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
