//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TabProj.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TABPROTYPE                  129
#define IDR_TABCONTEXT                  10049
#define IDM_TAB_BUTTON                  40000
#define IDM_TAB_BOTTOM                  40001
#define IDM_TAB_FLAT                    40002
#define IDM_SELECTOR_G1                 50052
#define IDM_SELECTOR_G2                 50053
#define IDM_SELECTOR_G3                 50054
#define IDM_SELECTOR_G4                 50055
#define IDM_SELECTOR_G5                 50056
#define IDM_SELECTOR_G6                 50057
#define IDM_SELECTOR_G7                 50058
#define IDM_SELECTOR_G8                 50059
#define IDM_SELECTOR_G9                 50060
#define IDM_SELECTOR_G10                50061
#define IDM_REPLACE_VIEW1               50062
#define IDM_REPLACE_VIEW2               50063
#define IDM_REPLACE_VIEW3               50064
#define IDM_REPLACE_VIEW4               50065
#define IDM_REPLACE_VIEW5               50066
#define IDM_REPLACE_VIEW6               50067
#define IDM_REPLACE_VIEW7               50068
#define IDM_REPLACE_VIEW8               50069
#define IDM_REPLACE_VIEW9               50070
#define IDM_REPLACE_VIEW10              50071
#define IDM_REPLACE_VIEW11              50072
#define IDM_REPLACE_VIEW12              50073
#define IDM_REPLACE_VIEW13              50074
#define IDM_REPLACE_VIEW14              50075
#define IDM_REPLACE_VIEW15              50076

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         50077
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
