//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DocumentBar.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DOCUMETYPE                  129
#define IDB_MENU_BUTTON                 131
#define IDC_BUTTON1                     1001
#define IDC_HANDCUR                     5005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
